version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: cd web
      - restore_cache:
          keys:
            - web-deps-{{ checksum "package.json" }}
            - web-deps-
      - run: npm i
      - save_cache:
          paths: node_modules
          key: web-deps-{{ checksum "package.json" }}
      - run: npm build
      - run: pwd
      - persist_to_workspace:
          root: web/dist

  deploy:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - main-deps-{{ checksum "package.json" }}
            - main-deps-
      - run: npm i
      - save_cache:
          paths: node_modules
          key: main-deps-{{ checksum "package.json" }}
      - attach_workspace:
          at: web/dist
      - run: npm run deploy:hosting:ci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: master
