version: 2
jobs:
  build:
    working_directory: ~/app/web
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          keys:
            - web-deps-{{ checksum "package.json" }}
            - web-deps-
      - run: npm i
      - save_cache:
          paths: node_modules
          key: web-deps-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths: 
            - dist

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          keys:
            - main-deps-{{ checksum "package.json" }}
            - main-deps-
      - run: npm i
      - save_cache:
          paths: node_modules
          key: main-deps-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/app/web
      - run: npm run deploy:hosting:ci

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: master
